# Generated by Django 5.1.6 on 2025-04-06 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="farm",
            name="area",
            field=models.FloatField(
                default=1.0, help_text="Farm area in acres or hectares"
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="user_crop_preferences",
            field=models.CharField(
                blank=True,
                choices=[
                    ("wheat", "Wheat"),
                    ("rice", "Rice"),
                    ("corn", "Corn"),
                    ("vegetables", "Vegetables"),
                    ("fruits", "Fruits"),
                    ("maize", "Maize"),
                    ("barley", "Barley"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="recommended_crop",
            field=models.CharField(
                blank=True,
                choices=[
                    ("wheat", "Wheat"),
                    ("rice", "Rice"),
                    ("corn", "Corn"),
                    ("vegetables", "Vegetables"),
                    ("fruits", "Fruits"),
                    ("maize", "Maize"),
                    ("barley", "Barley"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
