# Generated by Django 5.1.7 on 2025-04-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0003_alter_farm_climate_alter_farm_recommended_crop_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PricePrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crop", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("predicted_price", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
