# Generated by Django 5.1.7 on 2025-04-14 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0004_priceprediction"),
    ]

    operations = [
        migrations.AddField(
            model_name="farm",
            name="planting_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="farm",
            name="yield_per_acre",
            field=models.FloatField(
                blank=True, help_text="Expected yield in quintals per acre", null=True
            ),
        ),
    ]
