# Generated by Django 5.1.6 on 2025-03-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_farmerprofile_governmentprofile_nonprofitprofile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"ordering": ["priority"]},
        ),
        migrations.AddField(
            model_name="customuser",
            name="priority",
            field=models.IntegerField(
                choices=[(1, "High"), (2, "Medium"), (3, "Low")], default=3
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("GOVERNMENT", "Government Office"),
                    ("NON_PROFIT", "Non-Profit Organization"),
                    ("FARMER", "Farmer"),
                ],
                default="FARMER",
                max_length=20,
            ),
        ),
    ]
